apiVersion: apps/v1
kind: Deployment
metadata:
  name: procurement-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: procurement-service
  template:
    metadata:
      labels:
        app: procurement-service
    spec:
      containers:
        - name: procurement-service
          image: procurement-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          env:
            - name: DATABASE_URL
              value: "postgresql://postgres:postgres@postgres-service:5432/postgres?schema=public"
            - name: JWT_SECRET
              value: "supersceterjwtkey"
            - name: PORT
              value: "8000"
